#!/usr/bin/env bash
# installs nginx with Holberton School in the index

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
