#!/usr/bin/env bash
# installs nginx, now with a redirect to woerm
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
A="|t|rewrite ^/redirect_me https://twitter.com/littleautomaton/status/1342210312829693952?s=21 permanent;"
sudo sed -i "/^server {/a $A" /etc/nginx/sites-available/default
sudo sed -i "s/|t|/$(echo a | tr 'a' '\t')/g" /etc/nginx/sites-available/default
sudo service nginx start
