#!/usr/bin/env bash
# installs nginx with Holberton School in the index, with a redirect to woerm

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/^server {/a ::t::rewrite ^/redirect_me https://twitter.com/littleautomaton/status/1342210312829693952?s=21 permanent;" /etc/nginx/sites-available/default
# this is just so i can get a tab character to match formatting.
sudo sed -i "s/::t::/$(echo a | tr 'a' '\t')/" /etc/nginx/sites-available/default
sudo service nginx start
