#!/usr/bin/env bash
# installs haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
A="frontend jwow.tech\n\tbind *:80\n\tdefault_backend web_servers\n\n"
B="backend web_servers\n\tbalance roundrobin\n\tserver 1797-web-01 35.231.55.129:80\n\tserver 1797-web-02 35.237.225.123:80"
echo -e "$A$B" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
