#!/usr/bin/env bash
# this script displays To infinity and beyond infinitely, and is immune to SIGTERM
trap "echo I am invincible!!!" SIGTERM
loop=true
while [ $loop ]
do
	echo "To infinity and beyond"
	sleep 2
done

